# theme: minima

siteConfig:
    title: Zyrouge's Blog
    url: https://blog.zyrouge.gq/
    author: Zyrouge
    email: me@zyrouge.gq
    description: Write an awesome description for your new site here. You can edit this line in saber-config.yml. It will appear in your document head meta (for Google search results) site description.
    tags:
        expressjs:
            bgColor: bg-green-400
        discordjs:
            bgColor: bg-blue-400
        nodejs:
            bgColor: bg-green-600
        sequelize:
            bgColor: bg-blue-600
        default:
            bgColor: bg-indigo-600
    authors:
        Zyrouge:
            fullName: Zyrouge
            image: /images/zyrouge.png

themeConfig:
    nav:
        - text: Home
          link: /
        - text: About
          link: /about.html
    social:
        twitter: _zyrouge_
        github: zyrouge
        rss: true

plugins:
    - resolve: saber-plugin-query-posts
    - resolve: saber-plugin-feed
      options:
          atomFeed: true
    - resolve: saber-plugin-prismjs

markdown:
    lineNumbers: true

build:
    outDir: "docs"
